language: node_js

node_js:
- '12'

services:
- mongodb

sudo: false

before_script:
- npm install -g coveralls lerna jest@23.6.0 npm-local-development
- lerna bootstrap --hoist
- sleep 2 # thanks mongo

script:
- jest --coverage --forceExit --detectOpenHandles --runInBand
- cat ./coverage/lcov.info | coveralls
